### ISSUE TITLE
z_put.py example is not compatible with  0.10.0-rc

### ISSUE THREAD

**Issue by maxikrie** [eclipse-zenoh/zenoh-python#112]
### Describe the bug

There seem to be several issues at least with z_put.py in the latest release.

The Encoding library needs to imported from zenoh (line 20). Also the key expressions in the commented examples should not have a trailing '/'. Finally, I cannot get the JSON example to run. It throws following error:

raise TypeError("`encoding` was passed, but `payload` is not of type `bytes`")
TypeError: `encoding` was passed, but `payload` is not of type `bytes`

### To reproduce

1. add missing Encoding library, uncomment JSON example, and remove trailing '/' from key expression in z_put.py
2. python3 z_put.py

### System info

zenoh 0.10.0-rc

**Comment by YuanYuYuan** [comment]
@p-avital can you help check this?
