### ISSUE TITLE
Failure to sync with eclipse-zenoh/zenoh

### ISSUE THREAD

**Issue by fuzzypixelz** [eclipse-zenoh/zenoh-python#177]
### Describe the release item

[Currently zenoh-python fails to sync with eclipse-zenoh/zenoh.](https://github.com/eclipse-zenoh/ci/actions/runs/8623895565/job/23637938678)

Pull request #173 attempts to fix this, but the CI fails for a yet unknown reason.

**Comment by milyin** [comment]
Works ok now
