### ISSUE TITLE
Custom messages

### ISSUE THREAD

**Issue by aaronchongth** [eclipse-zenoh/zenoh-python#27]
Hello there! I tried out the examples and managed to get them working. I was wondering if there is a recommended way to generate custom messages to be used with `zenoh-python`, for example by ingesting an `.idl` file? 

So far, I have managed to use `pickle` to serialize python containers to be sent, and deserialize them when received.

**Comment by JEnoch** [comment]
Hi Aaron,

there is no specific recommendation for the serialization format of your data.

Using the **RAW** encoding, zenoh considers your data as a bytes array and doesn't try to deserialize it. You're free to use whatever serialization format with this encoding. As long as the publisher of the data and those that will get it (subscribing or querying) all agree on the serialization format, they will understand each other.

The other encoding specified by zenoh (string, properties, JSON...) will be used by the zenoh storages to deserialize the stored data in a known format and be able to:
 - store the data in a specific way depending on the backend. For instance the "SQL" encoding implies that the data is represented as an SQL row including column names. Thus, an SQL backend can store the data in a SQL table, checking that the data format fits in this table.
 - reply to queries with content filters (e.g. `GET "/demo/robots/*/position?(x>10&y>20)"` ). But this feature is not yet implemented.

**Comment by kydos** [comment]
Hello @aaronchongth, thanks for trying out zenoh! If you have any questions do not hesitate to post on our gitter channel  https://gitter.im/atolab/zenoh. 

@JEnoch already provided with one of the way to deal with IDL. By leveraging zenoh's RAW types for transporting CDR encoded IDL types everything will work like a charm. 

On my side I am a little bit curious of your use case so to understand if there is another approach we can  suggest that may be more appropriate. 

A+

**Comment by kydos** [comment]
Hello again @aaronchongth, 

   BTW, if you are looking into zenoh, something else you may want to tryout is our new version. The new version is being entirely rewritten in Rust and will support peer-to-peer as well as routed communication for all APIs (notice that the current version the Python API only works with a zenoh router/broker).

If you want to give a try at the Rust version and get a taste of the performance we get, here is what you need to do:


```
$ git clone git@github.com:atolab/zenoh.git
$ cd zenoh 
$ git checkout rust-master
$ cargo build --release
$ cargo build --release --examples

# then run the throughput benchmark

# run the subscriber
$ cargo run --release --example zn_sub_thr 

# run the publisher with <payload size> (1024 below) and locator 
# the locator will become optional  once  the rust version will also support  zenoh scouting 

$ cargo run --release --example zn_pub_thr  1024 tcp://127.0.0.1:7447
```

**Comment by aaronchongth** [comment]
Thanks for the explanation @JEnoch ! 

Hello @kydos ! I'll use gitter for any follow-up questions. and will definitely try out the `rust` implementation, looks awesome :D 

We are looking into middleware alternatives for robot-server communication in large network-constrained environments, https://github.com/osrf/free_fleet. We are currently using `CycloneDDS` which works great! However we anticipate discovery times to become an issue as we scale into larger environments, more robots and more unknown network issues. 

I will close this issue, as the main question has been resolved, thanks all!
