### ISSUE TITLE
In zenoh-python, example usage seems to be wrong

### ISSUE THREAD

**Issue by vinnnyr** [eclipse-zenoh/zenoh-python#32]
Hello,

In examples/zenoh/README.md , I am not able to use the examples as shown:
```
  python3 z_put
```

As I get a "file not found" error. I am on Mac OS X 10.15.6 and python 3.8.2  , pip3 21.01 (but have seen this issue on Ubuntu 20.04 as well). 
Instead I have to go into that directory and do this:
```
python3 z_put.py
```

Is there something wrong with my python installation of this package, or is the example wrong?

**Comment by JEnoch** [comment]
Hi @vinnnyr ,

The instructions in README.md are wrong. You indeed need to use the complete filename (with `.py` extension) in all commands.
Thanks to report this! I fix this now.

**Comment by vinnnyr** [comment]
Also, the `z_put_float` example no longer exists, correct ?

**Comment by JEnoch** [comment]
Correct! It has been replaced by a simple comment in z_put.py to explain how to publish a float.
I remove it from README.md. Thanks again!
