### ISSUE TITLE
zenoh python subscriber work with asyncio 

### ISSUE THREAD

**Issue by Yingliangzhe** [eclipse-zenoh/zenoh-python#34]
I would like to integrate the zenoh python with the asyncio library. 
The statement like following:
`sub = session.declare_subscriber('/rt/hello_world', sub_info, hello_callback)` will call the `hello_callback` function. 
The argument for the `hello_callback` can only be the sample: Sample. 
Inside the `hello_callback` I can only `deserialize` the received message. 

Is it possible, that I inside the `hello_callback` call a coroutine? Because I want to send the message to another broker(NATS broker) for further usage. But I need to call a coroutine to send the message to that broker. 
I have tried once to decorate the `hello_callback` function as a async function. But it failed. 

Or another alternative, that the recevied message can be stored in the Subscriber instance. The message can then be accessed.

**Comment by JEnoch** [comment]
I'm not familiar with the Python asyncio library. But after a glance, it looks similar to the async library we use in Rust.  
Thus, it's certainly a good idea to have a direct mapping of the zenoh Rust async API to a zenoh Python asyncio API !  
For this we would need to explore if/how [PyO3](https://github.com/PyO3/PyO3) would allow this. But I'm not sure it will be straight forward...

In the meantime, did you try in your `hello_callback` function to create a task calling your coroutine? Something like:
```python
async def fwd_to_nats(data):
   ...

def hello_callback(change):
   task = asyncio.create_task(fwd_to_nats(change.value.get_content()))

```

**Comment by JEnoch** [comment]
Note: this project might help a lot for an asyncio API:
https://github.com/awestlake87/pyo3-asyncio

**Comment by Yingliangzhe** [comment]
> I'm not familiar with the Python asyncio library. But after a glance, it looks similar to the async library we use in Rust.
> Thus, it's certainly a good idea to have a direct mapping of the zenoh Rust async API to a zenoh Python asyncio API !
> For this we would need to explore if/how [PyO3](https://github.com/PyO3/PyO3) would allow this. But I'm not sure it will be straight forward...
> 
> In the meantime, did you try in your `hello_callback` function to create a task calling your coroutine? Something like:
> 
> ```python
> async def fwd_to_nats(data):
>    ...
> 
> def hello_callback(change):
>    task = asyncio.create_task(fwd_to_nats(change.value.get_content()))
> ```

Thank you for your reply. If the zenoh python API support python asyncio straight forword, that would be really nice. 
I actually tried something similiar like your suggestion. By defining a async function `fwd_to_nats`  in python, I checked a queue, which stores the `sample` in `hello_callback` function. And this `fwd_to_nats` function has also been added to the eventloop, to get scheduled by the loop.

**Comment by Yingliangzhe** [comment]
I have still a question about the `callback` function for the `declare_subscriber`. Is it possible to return the value from the `callback` function to somewhere. I didn't see such a attribute in the class Subscriber.

**Comment by JEnoch** [comment]
>  By the way, is there also a defined future object in rust inside the callback function like `hello_callback` for subscriber ? Or it is defined in the `declare_subscriber` function?

In the Rust zenoh-net API, the [`declare_subscriber`](https://docs.rs/zenoh/0.5.0-beta.8/zenoh/net/struct.Session.html#method.declare_subscriber) function doesn't take a callback as parameter, but returns a future of a [`Subscriber`](https://docs.rs/zenoh/0.5.0-beta.8/zenoh/net/struct.Subscriber.html) that manages an async_std Stream. I think it's similar to [Python asyncio Streams](https://docs.python.org/3/library/asyncio-stream.html).

You can see its usage in the [zn_sub.rs example](https://github.com/eclipse-zenoh/zenoh/blob/5c1d3e8853b17d9ce2313a1e5207a8ef64049122/zenoh/examples/zenoh-net/zn_sub.rs#L38)

The Rust zenoh-net API also defines a [`declare_callback_subscriber`](https://docs.rs/zenoh/0.5.0-beta.8/zenoh/net/struct.Session.html#method.declare_callback_subscriber) function that takes a callback function which is non-async (see `DataHandler` signature).

> I have still a question about the `callback` function for the `declare_subscriber`. Is it possible to return the value from the `callback` function to somewhere. I didn't see such a attribute in the class Subscriber.

Sorry, I'm not sure to understand what you mean with _"return the value to somewhere"_.  
In the implementation of the `callback` you can call any other function passing the received value as an argument - except maybe an `async` function if Python doesn't allow to call an `async` from non-`async` code.
