### ISSUE TITLE
[Bug/Breaking Change] session.get tuple callback no longer works in 1.0.0

### ISSUE THREAD

**Issue by fsteff** [eclipse-zenoh/zenoh-python#364]
### Describe the bug

Is it on purpose that the option of passing a tuple as session.get handler no longer works in 1.0.0?
Instead it is necessary to wrap it into a `handlers.Callback` (i expected that this would happen automatically)

IMHO that's an unnecessary breaking change and I could not find any documentation about this change.
At least this should be documented in the 0.11.0 -> 1.0.0 migration section. Thanks :-) 

### To reproduce

```
import zenoh

session = zenoh.open(zenoh.Config())

def on_reply(reply):
    print('reply')

def on_done():
    print('done')

def on_query(query: zenoh.Query):
    query.reply(query.key_expr, 'test')

qable = session.declare_queryable('test', on_query)
session.get('test', (on_reply, on_done))
```
 result: only "reply" is written to the console

workaround / breaking change :
```
 session.get('test', zenoh.handlers.Callback(on_reply, on_done))
```

### System info

- zenoh version: `1.0.0-rc.2`

**Comment by wyfo** [comment]
The Python bindings have been rewritten from scratch for 1.0, trying to match more carefully the Rust API. In Rust, a tuple handler has the meaning `(callback, handler)`, not `(callback, drop_callback)`.
I think it's too late to rollback to the old behavior, but that's indeed a breaking change that should be mentioned in bold in the migration guide.
