### ISSUE TITLE
Get testing failure with the pull-subscriber example

### ISSUE THREAD

**Issue by eddie9712** [eclipse-zenoh/zenoh-python#40]
Hi all,
When I tried to use use the python API `zn_pull.py`, I got the error below:
```
Traceback (most recent call last):
File "zn_pull.py", line 61, in listener
sample.data_info.timestamp.time)
AttributeError: 'NoneType' object has no attribute 'time'
``` 
I guessed that it couldn't get the timestamp of the sample(I couldn't get timestamps with other zenoh-net examples either), after I edited the code of timestamp handling to 
`time = '(not specified)' if sample.data_info is None or sample.data_info.timestamp is None else datetime.fromtimestamp( sample.data_info.timestamp.time)`
it worked.

I am not sure whether my guess is correct or not, thank you

**Comment by JEnoch** [comment]
Hi @eddie9712,
thanks for spotting this! Your guess is correct, the timestamp is not present in this case.

By default the timestamp is not set by the zenoh or zenoh-net API at publication (but that's configurable).
It's set by the first zenoh router that routes a un-timestamped data, or by the zenoh API at reception of a un-timestamped data.
