### ISSUE TITLE
[Bug] Subscriber.undeclare blocks in some cases [v1.0.4]

### ISSUE THREAD

**Issue by fsteff** [eclipse-zenoh/zenoh-python#412]
### Describe the bug

After updating from zenoh-python `1.0.3` to `1.0.4` I am having issues with a call to `subscriber.undeclare()` never returning.
I am not using the context manager feature, instead I call `undeclare` manually.
The call happens within an async function, effectively blocking the whole asyncio event loop.

### To reproduce

Sorry, I was not able to reproduce this in a simple example.

### System info

- Platform Win11
- Python `3.10.9`
- zenoh-python `1.0.4` (works fine with `1.0.3`)
- Asyncio-based application

**Comment by wyfo** [comment]
The bug has been identified and patch yesterday, see https://github.com/eclipse-zenoh/zenoh/pull/1649 and https://github.com/eclipse-zenoh/zenoh/issues/1650
It will be fixed in 1.1.0 version which should be released soon this week.
