### ISSUE TITLE
Update pyo3 to 0.15.0

### ISSUE THREAD

**Issue by 0xbentang** [eclipse-zenoh/zenoh-python#44]
I'm getting the following error:

```
thread 'blocking-1' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`: Python threading is not initalized and the `auto-initialize` feature is not enabled.

Consider calling `pyo3::prepare_freethreaded_python()` before attempting to use Python APIs.', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.14.5/src/gil.rs:232:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'async-std/runtime' panicked at 'task has failed', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45
```

It should be fixed in pyo3 0.15.0 https://github.com/PyO3/pyo3/issues/1870

**Comment by JEnoch** [comment]
zenoh-python have been ported to pyo3 0.15 in the `apis-merge` [branch](https://github.com/eclipse-zenoh/zenoh-python/tree/apis-merge). 
This branch provides a new API for zenoh that remains as close as possible of the former `zenoh` API, but to also allow all the fine tuning of the protocol that the `zenoh-net` API allows via `kwargs` options. It will be merged into the `master` branch today (or in the next few days at the latest).
Can you please try with this new API ?

**Comment by Mallets** [comment]
Closing since `apis-merge` has been merged into `master`.
