### ISSUE TITLE
Problems with "hello world"

### ISSUE THREAD

**Issue by femust** [eclipse-zenoh/zenoh-python#54]
Hey so I am trying to run

```
python3 z_sub.py
```
and I get the following error:
```
Traceback (most recent call last):
  File "z_sub.py", line 20, in <module>
    from zenoh import Reliability, SubMode
ImportError: cannot import name 'Reliability' from 'zenoh' (/home/andrzej/.local/lib/python3.8/site-packages/zenoh/__init__.py)

```
What should I do? Do you think that maybe I have missed versions 0.6 and 0.5? Because even I can't change the zenoh.__version__ for some reasons....

**Comment by JEnoch** [comment]
I think you're using an old version of zenoh-python that cannot work with latest examples.
Please try to do:

**Comment by akila-ganlath-tm** [comment]
This did the trick for me @JEnoch
