### ISSUE TITLE
[Bug] init_logger may panic if called from enviroment where the logger was already initialized (e.g., PyO3)

### ISSUE THREAD

**Issue by gabrik** [eclipse-zenoh/zenoh-python#61]
### Describe the bug

When the `zenoh.init_logger()` function is called from an environment where `env_logger` was already initialized it crashes with the following error:

```
 PyErr { type: <class 'pyo3_runtime.PanicException'>, value: PanicException('env_logger::init should not be called after logger initialized: SetLoggerError(())'),
```

This is well documented in the [`env_logger`](https://docs.rs/env_logger/latest/env_logger/fn.init.html) crate.

A solution is to use [`try_init`](https://docs.rs/env_logger/latest/env_logger/fn.try_init.html) which returns an error instead of panicking, so change [this line](https://github.com/eclipse-zenoh/zenoh-python/blob/master/src/lib.rs#L159) to something like

```rust
env_logger::try_init().unwrap_or_else(|_| log::warn!("`env_logger` already initialized"));;
```

It will avoid crashed and print in the log that the logger was already initialized.

### To reproduce

Run `zenoh.init_logger()` in an environment with the logger already initialized (e.g. calling it from PyO3)

### System info

Not applicable

**Comment by p-avital** [comment]
Fixed in `api-changes` branch :)
